Promotes ISC machinefrom sandbox to production
m-lab/siteinfo pull request #322
Opened 2024-02-29 23:35 UTC by nkinkade

The test of the ISC "minimal" site with a single server and a /28 IPv4 prefix was successful in mlab-sandbox, and I believe we can now promote that machine to a new production site.

2024-02-29 23:38 UTC, stephen-soltesz reviewed
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/322)* status: 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`sites/nuq08.jsonnet` line 6 at r1](https://reviewable.io/reviews/m-lab/siteinfo/322#-NrrDkk_97s1mKgAr_Mb:-NrrDkk_97s1mKgAr_Mc:bynjovp) ([raw file](https://github.com/m-lab/siteinfo/blob/e03491312e043c28348f747951f75b669cba168b/sites/nuq08.jsonnet#L6)):*
> ```Jsonnet
>   name: 'nuq08',
>   annotations+: {
>     type: 'physical',
> ```

Will data collected on this node include metadata that indicates it is a "minimal" site configuration? How will we know for analysis that a given site is one configuration or the other?

The network prefix allows our configuration management to know. Is this distinction propagated to the data?


<!-- Sent from Reviewable.io -->

2024-02-29 23:58 UTC, nkinkade reviewed
I also just realized that the max-rate value for ndt-server is probably incorrect for the test ISC minimal site. We statically set 10G site machines to a max-rate of 2.5Gbps:

https://github.com/m-lab/siteinfo/blob/main/formats/v2/sites/max-rates.json.jsonnet

I imagine that since minimal sites consist only of a single machine, that the max-rate should probably be closer to the link speed. We should be able to modify this siteinfo format to account for minimal sites:

https://github.com/m-lab/siteinfo/blob/main/formats/v2/sites/max-rates.json.jsonnet

> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/322#-:-NrrGREE0oWUP1FYkHaK:bcbg10o)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`sites/nuq08.jsonnet` line 6 at r1](https://reviewable.io/reviews/m-lab/siteinfo/322#-NrrDkk_97s1mKgAr_Mb:-NrrFql54Nb942LnjUSb:bnlvdf3) ([raw file](https://github.com/m-lab/siteinfo/blob/e03491312e043c28348f747951f75b669cba168b/sites/nuq08.jsonnet#L6)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Will data collected on this node include metadata that indicates it is a "minimal" site configuration? How will we know for analysis that a given site is one configuration or the other?

The network prefix allows our configuration management to know. Is this distinction propagated to the data?
</blockquote></details>

I don't think this distinction is currently propagated to the data in any way. Is it important to be able to filter on minimal sites in BQ queries? If so, then it should be fairly easy to get a local metadata value written:

https://github.com/m-lab/epoxy-images/blob/main/configs/stage3_ubuntu/opt/mlab/bin/write-metadata.sh

... and then ingested by ndt-server with some flag like `-label=<name>=@/var/local/metadata/<name>'`

We'd just have to decide what the name of the new metadata value would be, and what the value would be for "full" or "minimal" sites, and whether we'd want to make a distinction between /28 and /29 minimal sites.


<!-- Sent from Reviewable.io -->

2024-03-01 00:34 UTC, stephen-soltesz reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/322)* status: 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`sites/nuq08.jsonnet` line 6 at r1](https://reviewable.io/reviews/m-lab/siteinfo/322#-NrrDkk_97s1mKgAr_Mb:-NrrOmQH81BgSM5n5mLa:bspa50l) ([raw file](https://github.com/m-lab/siteinfo/blob/e03491312e043c28348f747951f75b669cba168b/sites/nuq08.jsonnet#L6)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I don't think this distinction is currently propagated to the data in any way. Is it important to be able to filter on minimal sites in BQ queries? If so, then it should be fairly easy to get a local metadata value written:

https://github.com/m-lab/epoxy-images/blob/main/configs/stage3_ubuntu/opt/mlab/bin/write-metadata.sh

... and then ingested by ndt-server with some flag like `-label=<name>=@/var/local/metadata/<name>'`

We'd just have to decide what the name of the new metadata value would be, and what the value would be for "full" or "minimal" sites, and whether we'd want to make a distinction between /28 and /29 minimal sites.
</blockquote></details>

I do believe it's important to know the environment and conditions under which the measurement data was collected. We isolate full sites behind a switch to prevent any cross traffic from interfering with our measurements on the first hop. That may not be the case for minimal sites. We want to be able to tell them apart.

I'll continue to consider names. The metadata label sounds like a fine mechanism. My first instinct is to label the two dimensions related to the support models: switch or not, m-lab managed or not. That would give us, (yes, yes), (no, yes), and (no, no) for the three models we're considering.


<!-- Sent from Reviewable.io -->

2024-03-01 16:13 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/322)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`sites/nuq08.jsonnet` line 6 at r1](https://reviewable.io/reviews/m-lab/siteinfo/322#-NrrDkk_97s1mKgAr_Mb:-NrukHpa1FsLEjNgN4Ag:b-i6rhqu) ([raw file](https://github.com/m-lab/siteinfo/blob/e03491312e043c28348f747951f75b669cba168b/sites/nuq08.jsonnet#L6)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I do believe it's important to know the environment and conditions under which the measurement data was collected. We isolate full sites behind a switch to prevent any cross traffic from interfering with our measurements on the first hop. That may not be the case for minimal sites. We want to be able to tell them apart.

I'll continue to consider names. The metadata label sounds like a fine mechanism. My first instinct is to label the two dimensions related to the support models: switch or not, m-lab managed or not. That would give us, (yes, yes), (no, yes), and (no, no) for the three models we're considering.
</blockquote></details>

I though we used a switch because there was no alternative to using one. The provider gives us a single port on their equipment (usually a router, most likely) and we have to connect 4 machines through that single port, necessitating a switch. That is, I didn't think the switch was an architectural option for the purposes of isolating traffic and improving measurement quality. Indeed, the switch most likely introduces some small degradation in performance, though it may not be significant for the purposes of measuring throughput.

We already have the field `server.Network.CIDR`, from which we could infer that a site is "full" or "minimal" based on the prefix length. But maybe you are thinking that an inference isn't good enough, and that an explicit label should be required. It's hard for me to imagine which researcher or regulator would ever really care whether a measurement was conducted at a site with single machine, or one with 4 machine through a switch. Are you thinking that the distinction would largely only be relevant to M-Lab for the purposes of determining whether measurement quality was affected by the lack of a switch?


<!-- Sent from Reviewable.io -->

2024-03-04 17:43 UTC, stephen-soltesz requested changes
The max-rates for 1G machines are still probably correct given the availability of high-speed clients.

The max-rates for 10G machines could be higher. I think somewhere else you suggested 7.5G which makes sense to me. It's kind of like one node standing in for three, with headroom large enough for one or two high capacity clients.

> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/322#-:-Ns9WNcu0nPApNWsjkOZ:b-eczcdv)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`sites/nuq08.jsonnet` line 6 at r1](https://reviewable.io/reviews/m-lab/siteinfo/322#-NrrDkk_97s1mKgAr_Mb:-Ns9Ks5t0roOwUwaA3IS:b-lnvk1a) ([raw file](https://github.com/m-lab/siteinfo/blob/e03491312e043c28348f747951f75b669cba168b/sites/nuq08.jsonnet#L6)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I though we used a switch because there was no alternative to using one. The provider gives us a single port on their equipment (usually a router, most likely) and we have to connect 4 machines through that single port, necessitating a switch. That is, I didn't think the switch was an architectural option for the purposes of isolating traffic and improving measurement quality. Indeed, the switch most likely introduces some small degradation in performance, though it may not be significant for the purposes of measuring throughput.

We already have the field `server.Network.CIDR`, from which we could infer that a site is "full" or "minimal" based on the prefix length. But maybe you are thinking that an inference isn't good enough, and that an explicit label should be required. It's hard for me to imagine which researcher or regulator would ever really care whether a measurement was conducted at a site with single machine, or one with 4 machine through a switch. Are you thinking that the distinction would largely only be relevant to M-Lab for the purposes of determining whether measurement quality was affected by the lack of a switch?
</blockquote></details>

I think you're right that having a switch is more convenient for having multiple machines than needing multiple ports. I'm sure I remember sstuart describing it as isolation as well, but I may have misunderstood or just can't reproduce the rationale. We can monitor the switch traffic but can't monitor the router traffic. So, for data analysis or operational management we can known when we're the issue or not better with a switch than without one.

I'm glad that there are additional ways to infer the site configuration (e.g. from server.Network.CIDR). My main thinking is putting all the important information into the same place (e.g. ServerMetadata) rather than across N columns, and for the metadata to be self-describing. We need to know how M-Lab is architected to appreciate the differences between /26 and /28. If there's a label or column that spells that out, all the better.

This is about measurement quality, to what degree can we attest to it or not, and how easy analysts can verify or filter based on it. With this in production soon, we'll have a need for a resource archiving agent like disco but for local resources only.

How about labels for: managed switch (yes or no), managed node (yes or no):

managed-switch=yes
managed-node=yes

managed-switch=no
managed-node=yes

etc.

We want to document them here: https://docs.google.com/document/d/1xe1AJQhIyjeY1wAXg7KikAJYDJB27kAt1_SxAFsjsxo/edit 


<!-- Sent from Reviewable.io -->

2024-03-13 17:35 UTC, nkinkade reviewed
The max-rate issue was resolved by [a separate PR](https://github.com/m-lab/siteinfo/pull/324).

> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/322#-:-NsssG3CAG7q_32JtB9E:b-2jbfkg)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`sites/nuq08.jsonnet` line 6 at r1](https://reviewable.io/reviews/m-lab/siteinfo/322#-NrrDkk_97s1mKgAr_Mb:-NssrPTa136h7J_xrzQF:b51p9eu) ([raw file](https://github.com/m-lab/siteinfo/blob/e03491312e043c28348f747951f75b669cba168b/sites/nuq08.jsonnet#L6)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I think you're right that having a switch is more convenient for having multiple machines than needing multiple ports. I'm sure I remember sstuart describing it as isolation as well, but I may have misunderstood or just can't reproduce the rationale. We can monitor the switch traffic but can't monitor the router traffic. So, for data analysis or operational management we can known when we're the issue or not better with a switch than without one.

I'm glad that there are additional ways to infer the site configuration (e.g. from server.Network.CIDR). My main thinking is putting all the important information into the same place (e.g. ServerMetadata) rather than across N columns, and for the metadata to be self-describing. We need to know how M-Lab is architected to appreciate the differences between /26 and /28. If there's a label or column that spells that out, all the better.

This is about measurement quality, to what degree can we attest to it or not, and how easy analysts can verify or filter based on it. With this in production soon, we'll have a need for a resource archiving agent like disco but for local resources only.

How about labels for: managed switch (yes or no), managed node (yes or no):

managed-switch=yes
managed-node=yes

managed-switch=no
managed-node=yes

etc.

We want to document them here: https://docs.google.com/document/d/1xe1AJQhIyjeY1wAXg7KikAJYDJB27kAt1_SxAFsjsxo/edit
</blockquote></details>

@stephen-soltesz: following up on this PR, per the discussion at the weekly engineering call. I believe we have decided to go with a single label that can have multiple values, for example:

managed=switch,machines <- for the case of full deployments
managed=machines <- for the base of minimal deployments
managed=none <- for the case of BYOS

Tiny detail, do we care whether "machine" is plural or singular? In the case of full sites, plural is more accurate, but is not accurate in the case of minimal sites. Maybe singular is better?


<!-- Sent from Reviewable.io -->

2024-03-13 19:00 UTC, stephen-soltesz reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/322)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`sites/nuq08.jsonnet` line 6 at r1](https://reviewable.io/reviews/m-lab/siteinfo/322#-NrrDkk_97s1mKgAr_Mb:-NstAJuyAX31rrvts6kh:b-slihkf) ([raw file](https://github.com/m-lab/siteinfo/blob/e03491312e043c28348f747951f75b669cba168b/sites/nuq08.jsonnet#L6)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

@stephen-soltesz: following up on this PR, per the discussion at the weekly engineering call. I believe we have decided to go with a single label that can have multiple values, for example:

managed=switch,machines <- for the case of full deployments
managed=machines <- for the base of minimal deployments
managed=none <- for the case of BYOS

Tiny detail, do we care whether "machine" is plural or singular? In the case of full sites, plural is more accurate, but is not accurate in the case of minimal sites. Maybe singular is better?
</blockquote></details>

I recommend singular. Any data annotated with this label will be associated with an individual switch and an individual machine.

Is this now out of scope of this PR? (should I approve this PR now?)

Tangential: does MSAK have a facility for adding these kind of labels also?


<!-- Sent from Reviewable.io -->

2024-03-13 20:11 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/322)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`sites/nuq08.jsonnet` line 6 at r1](https://reviewable.io/reviews/m-lab/siteinfo/322#-NrrDkk_97s1mKgAr_Mb:-NstQlRF4lNyeBoFLqKC:b-jaa6aj) ([raw file](https://github.com/m-lab/siteinfo/blob/e03491312e043c28348f747951f75b669cba168b/sites/nuq08.jsonnet#L6)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I recommend singular. Any data annotated with this label will be associated with an individual switch and an individual machine.

Is this now out of scope of this PR? (should I approve this PR now?)

Tangential: does MSAK have a facility for adding these kind of labels also?
</blockquote></details>

Yes, I think this PR can now be approved. I would merge this PR, then implement change to write the new metadata and make sure that was implemented prior to sending this change to production.

I don't know about msak. A quick glace at the server code makes it seems like it doesn't have any sort of -label flag similar to ndt-server. But @robertodauria may know better. If that doesn't exist, then it should probably be added at some point.


<!-- Sent from Reviewable.io -->

2024-03-13 20:51 UTC, stephen-soltesz approved these changes
Thank you. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/322#-:-Nst_G7F2fuMV_PARINm:bt8gqw2)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @robertodauria)



<!-- Sent from Reviewable.io -->

2024-03-13 20:53 UTC, merged